
package co.unicauca.clientes.vista;

import co.unicauca.clientes.modelo.ClientesDB;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.Observable;

/**
 *
 * @author Libardo Pantoja, Ricardo Zambrano Es el primer primer observador.
 *
 */
public class GUIEstadisticaPorSexo extends javax.swing.JFrame implements java.util.Observer {

    private String profesion;
    
    /**
     * Constructor
     *
     * @param h horizontal position
     * @param v vertical position
     */
    public GUIEstadisticaPorSexo(int h, int v) {
        //observers = new ArrayList();
        initComponents();
        setSize(250, 200);
        setLocation(h, v);
        setVisible(true);
        //profesion = cboProfesion.getSelectedItem().toString();
    }

      @Override    
      public void update(Observable obs, Object obj) {        
          ClientesDB cliDB = (ClientesDB)obs;        
          txtHombres.setText("" + cliDB.getTotalHombres());        
          txtMujeres.setText("" + cliDB.getTotalMujeres());        
          this.setTitle("Estadísticas por sexo. Profesión: " 
                  + cliDB.getProfesion());    
      }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHombres = new javax.swing.JTextField();
        txtMujeres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda de Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Hombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Mujeres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 108, -1, -1));

        txtHombres.setEditable(false);
        txtHombres.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtHombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 42, 73, 39));

        txtMujeres.setEditable(false);
        txtMujeres.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 99, 73, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getProfesion() {
        return profesion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexo(100, 100).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHombres;
    private javax.swing.JTextField txtMujeres;
    // End of variables declaration//GEN-END:variables

  
}
